name: gz_static
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  flutter_svg: ^0.22.0
  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  intl: ^0.17.0
  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-SemiBold.ttf
    - family: Nunito_bold
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
    - family: Nunito_extra_bold
      fonts:
        - asset: assets/fonts/Nunito-ExtraBold.ttf

  assets:
    - assets/images/logo.png
    - assets/images/logotype.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
